### ISSUE TITLE
How to use pool for `connection.execute`

### ISSUE THREAD

**Issue by dcosson** [kickstarter/replica_pools#15]
I have replica_pools set up with one pool, and with `ReplicaPools.config.defaults_to_leader = true`

It's working and using my pool when I do activerecord queries within a `with_pool` block, but when I do a `connection.execute()` within the block it's still using the leader (this happens both for MyModel.connection.execute and ActiveRecord::Base.connection.execute).

Is there any way around this, so that `connection.execute` can use the pool as well?

**Comment by cainlevy** [comment]
Hi @dcosson,

ReplicaPools maintains a list of "safe" methods that it will confidently [proxy to the currently selected connection](https://github.com/kickstarter/replica_pools/blob/master/lib/replica_pools/connection_proxy.rb#L20-L26). Anything else is [always sent to the leader](https://github.com/kickstarter/replica_pools/blob/master/lib/replica_pools/connection_proxy.rb#L98-L104).

If you are confident that `connection.execute` may be safely proxied to a replica in your application, try configuring ReplicaPools as follows:

```ruby
ReplicaPools.config.safe_methods << :execute
```

The default list is available here: https://github.com/kickstarter/replica_pools/blob/master/lib/replica_pools/engine.rb#L11-L26

**Comment by dcosson** [comment]
Ah that makes sense. I guess in general the query could be a write which isn't safe to send to a replica?

Thanks for the response!
