### ISSUE TITLE
Referencing "ReplicaPools.pools" in initializers causes environment to be wrong

### ISSUE THREAD

**Issue by sgringwe** [kickstarter/replica_pools#16]
I have an initializer, and in that initializer I had the following code:

```
# Simple print statement to inform what ReplicaPools is doing when we boot.
ReplicaPools.pools.each do |key, value|
  puts "[ReplicaPools] Pool '#{key}' has replicas #{value.replicas.map(&:name)}"
end
```

In staging, I noticed that the pools were not picking up my database.yml config. It seems that if `ReplicaPools.pools` is evaluated in the initializer, it picks up the default environment of "development" since (I'm assuming here) the engine has not yet run its code at this point.

Preferred behavior: Referencing `ReplicaPools.pools` in initializer does not cause this bug.

**Comment by cainlevy** [comment]
Hi @sgringwe, thanks for reporting this. Seems like a definite gotcha! We would evaluate pull requests to fix.
