### ISSUE TITLE
rails 5 support

### ISSUE THREAD

**Issue by mattknox** [kickstarter/replica_pools#17]
It appears that very little is needed to support rails 5, other than changes here: https://github.com/kickstarter/replica_pools/blob/4758391ea1a7749e51ef98aba2f0a8f74b89e720/lib/replica_pools/engine.rb

Are y'all interested in a PR that does this update?

**Comment by tiegz** [comment]
@mattknox that would be great! difficult for us to test currently, but if you're willing to go for it 👍

**Comment by jgubman** [comment]
I also submitted a PR for rails 5 support at:
https://github.com/kickstarter/replica_pools/pull/18

**Comment by frewsxcv** [comment]
We at Kickstarter have been using_replica pools for a while without any issues, so feels safe to close this. If anyone is aware of issues, please open a new one, thanks!
